export type SHOW_COLUMNS = 'never' | true | false;
export type FORMAT_COLUMNS = 'datetime' | 'short' | 'date' | 'bool';
export type TYPE_COLUMNS = 'hide' | 'check' | 'cal' | 'radio' | 'input' | 'password' | 'disable' | 'popup' | 'auto' | 'switch' | 'mask' | 'number';

export interface Session {
    correlationId: number;
    token: string;
    id: number;
    firstname: string;
    lastname: string;
    role: Role;
}

export enum Role {
    USER = 'USER',
    ASSISTANT = 'ASSISTANT',
    MANAGER = 'MANAGER',
    ADMIN = 'ADMIN'
}

export const RoleType = [
    Role.USER,
    Role.ASSISTANT,
    Role.MANAGER,
    Role.ADMIN
];

export enum AccountType {
    STUDENT,
    PILOT,
    INSTRUCTOR,
    MECHANIC,
    INSPECTOR
}

export enum AddressType {
    Home = 'Home',
    Business = 'Business',
    Billing = 'Billing',
    Shipping = 'Shipping',
    Contract = 'Contract',
    Hangar = 'Hangar',
    Shelter = 'Shelter',
    Tiedown = 'Tiedown',
    Mailing = 'Mailing',
    Physycal = 'Physycal',
    Electronic = 'Electronic',
    Other = 'Other'
}

export const DocumentType = {
    Passport: ['Passport', 'Passport'],
    DriverLicense: ['DriverLicense', 'Driver License'],
    AlienResident: ['AlienResident', 'Alien Resident'],
    Visa: ['Visa', 'Visa'],
    PilotCertificate: ['PilotCertificate', 'Pilot Certificate'],
    MedicalCertificate: ['MedicalCertificate', 'Medical Certificate'],
    BirthCertificate: ['BirthCertificate', 'Birth Certificate'],
    TSATrainingCertificate: ['TSATrainingCertificate', 'TSA Awareness Training Certificate'],
    TSAFormI20: ['TSAFormI20', 'TSA Form I-20'],
    TSAPaymentReceived: ['TSAPaymentReceived', 'TSA Payment Received'],
    RentersInsuranceAgreement: ['RentersInsuranceAgreement', 'Renters Insurance Agreement'],
    Finance: ['Finance', 'Finance'],
    PrivatePilotPermission: ['PrivatePilotPermission', 'Private Pilot Permission'],
    InstrumentRatingPermission: ['InstrumentRatingPermission', 'Instrument Rating Permission'],
    MultiCommercialPermission: ['MultiCommercialPermission', 'Multi/Commercial Permission'],
    TrainingRequest: ['TrainingRequest', 'Training Request'],
    AircraftCheckoutRecord: ['AircraftCheckoutRecord', 'Aircraft Checkout Record'],
    PilotPicture: ['PilotPicture', 'Pilot Picture'],
    AddressProof: ['AddressProof', 'Address Proof of Residence'],
    OnlineDocument: ['OnlineDocument', 'Online Document'],
    Other: ['Other', 'Other']
};

export enum Country {
    AF = 'Afghanistan',
    AX = 'AlandIslands',
    AL = 'Albania',
    DZ = 'Algeria',
    AS = 'American Samoa',
    AD = 'Andorra',
    AO = 'Angola',
    AI = 'Anguilla',
    AQ = 'Antarctica',
    AG = 'Antigua and Barbuda',
    AR = 'Argentina',
    AM = 'Armenia',
    AW = 'Aruba',
    AU = 'Australia',
    AT = 'Austria',
    AZ = 'Azerbaijan',
    BS = 'Bahamas',
    BH = 'Bahrain',
    BD = 'Bangladesh',
    BB = 'Barbados',
    BY = 'Belarus',
    BE = 'Belgium',
    BZ = 'Belize',
    BJ = 'Benin',
    BM = 'Bermuda',
    BT = 'Bhutan',
    BO = 'Bolivia',
    BA = 'Bosnia and Herzegovina',
    BW = 'Botswana',
    BV = 'Bouvet Island',
    BR = 'Brazil',
    IO = 'British Indian Ocean Territory',
    BN = 'Brunei Darussalam',
    BG = 'Bulgaria',
    BF = 'Burkina Faso',
    BI = 'Burundi',
    KH = 'Cambodia',
    CM = 'Cameroon',
    CA = 'Canada',
    CV = 'Cape Verde',
    KY = 'Cayman Islands',
    CF = 'Central African Republic',
    TD = 'Chad',
    CL = 'Chile',
    CN = 'China',
    CX = 'Christmas Island',
    CC = 'Cocos Keeling Islands',
    CO = 'Colombia',
    KM = 'Comoros',
    CG = 'Congo',
    CD = 'Congo Democratic Republic',
    CK = 'Cook Islands',
    CR = 'Costa Rica',
    CI = 'CoteDIvoire',
    HR = 'Croatia',
    CU = 'Cuba',
    CY = 'Cyprus',
    CZ = 'CzechRepublic',
    DK = 'Denmark',
    DJ = 'Djibouti',
    DM = 'Dominica',
    DO = 'Dominican Republic',
    EC = 'Ecuador',
    EG = 'Egypt',
    SV = 'El Salvador',
    GQ = 'Equatorial Guinea',
    ER = 'Eritrea',
    EE = 'Estonia',
    ET = 'Ethiopia',
    FK = 'Falkland Islands',
    FO = 'Faroe Islands',
    FJ = 'Fiji',
    FI = 'Finland',
    FR = 'France',
    GF = 'French Guiana',
    PF = 'French Polynesia',
    TF = 'French Southern Territories',
    GA = 'Gabon',
    GM = 'Gambia',
    GE = 'Georgia',
    DE = 'Germany',
    GH = 'Ghana',
    GI = 'Gibraltar',
    GR = 'Greece',
    GL = 'Greenland',
    GD = 'Grenada',
    GP = 'Guadeloupe',
    GU = 'Guam',
    GT = 'Guatemala',
    GG = 'Guernsey',
    GN = 'Guinea',
    GW = 'Guinea Bissau',
    GY = 'Guyana',
    HT = 'Haiti',
    HM = 'Heard Island Mcdonald Islands',
    VA = 'Holy See Vatican City State',
    HN = 'Honduras',
    HK = 'HongKong',
    HU = 'Hungary',
    IS = 'Iceland',
    IN = 'India',
    ID = 'Indonesia',
    IR = 'Iran',
    IQ = 'Iraq',
    IE = 'Ireland',
    IM = 'Isle Of Man',
    IL = 'Israel',
    IT = 'Italy',
    JM = 'Jamaica',
    JP = 'Japan',
    JE = 'Jersey',
    JO = 'Jordan',
    KZ = 'Kazakhstan',
    KE = 'Kenya',
    KI = 'Kiribati',
    KR = 'Korea, Republic of',
    KP = 'Korea, Democratic People\'s Republic of',
    KW = 'Kuwait',
    KG = 'Kyrgyzstan',
    LA = 'Lao Peoples Democratic Republic',
    LV = 'Latvia',
    LB = 'Lebanon',
    LS = 'Lesotho',
    LR = 'Liberia',
    LY = 'Libyan Arab Jamahiriya',
    LI = 'Liechtenstein',
    LT = 'Lithuania',
    LU = 'Luxembourg',
    MO = 'Macao',
    MKD = 'Republic of North Macedonia',
    MG = 'Madagascar',
    MW = 'Malawi',
    MY = 'Malaysia',
    MV = 'Maldives',
    ML = 'Mali',
    MT = 'Malta',
    MH = 'Marshall Islands',
    MQ = 'Martinique',
    MR = 'Mauritania',
    MU = 'Mauritius',
    YT = 'Mayotte',
    MX = 'Mexico',
    FM = 'Micronesia',
    MD = 'Moldova',
    MC = 'Monaco',
    MN = 'Mongolia',
    ME = 'Montenegro',
    MS = 'Montserrat',
    MA = 'Morocco',
    MZ = 'Mozambique',
    MM = 'Myanmar',
    NA = 'Namibia',
    NR = 'Nauru',
    NP = 'Nepal',
    NL = 'Netherlands',
    NC = 'New Caledonia',
    NZ = 'New Zealand',
    NI = 'Nicaragua',
    NE = 'Niger',
    NG = 'Nigeria',
    NU = 'Niue',
    NF = 'Norfolk Island',
    MP = 'Northern Mariana Islands',
    NO = 'Norway',
    OM = 'Oman',
    PK = 'Pakistan',
    PW = 'Palau',
    PS = 'Palestinian Territory',
    PA = 'Panama',
    PG = 'Papua New Guinea',
    PY = 'Paraguay',
    PE = 'Peru',
    PH = 'Philippines',
    PN = 'Pitcairn',
    PL = 'Poland',
    PT = 'Portugal',
    PR = 'Puerto Rico',
    QA = 'Qatar',
    RE = 'Reunion',
    RO = 'Romania',
    RU = 'Russian Federation',
    RW = 'Rwanda',
    BL = 'Saint Barthelemy',
    SH = 'Saint Helena',
    KN = 'Saint Kitts And Nevis',
    LC = 'Saint Lucia',
    MF = 'Saint Martin',
    PM = 'Saint Pierre And Miquelon',
    VC = 'Saint Vincent And Grenadines',
    WS = 'Samoa',
    SM = 'San Marino',
    ST = 'Sao Tome And Principe',
    SA = 'Saudi Arabia',
    SN = 'Senegal',
    RS = 'Serbia',
    SC = 'Seychelles',
    SL = 'Sierra Leone',
    SG = 'Singapore',
    SK = 'Slovakia',
    SI = 'Slovenia',
    SB = 'Solomon Islands',
    SO = 'Somalia',
    ZA = 'South Africa',
    GS = 'South Georgia And Sandwich Island',
    ES = 'Spain',
    LK = 'Sri Lanka',
    SD = 'Sudan',
    SS = 'South Sudan',
    SR = 'Suriname',
    SJ = 'Svalbard And Jan Mayen',
    SZ = 'Swaziland',
    SE = 'Sweden',
    CH = 'Switzerland',
    SX = 'Sint Maarten (Dutch part)',
    SY = 'Syrian Arab Republic',
    TW = 'Taiwan',
    TJ = 'Tajikistan',
    TZ = 'Tanzania',
    TH = 'Thailand',
    TL = 'TimorLeste',
    TG = 'Togo',
    TK = 'Tokelau',
    TO = 'Tonga',
    TT = 'Trinidad And Tobago',
    TN = 'Tunisia',
    TR = 'Turkey',
    TM = 'Turkmenistan',
    TC = 'Turks And Caicos Islands',
    TV = 'Tuvalu',
    UG = 'Uganda',
    UA = 'Ukraine',
    AE = 'United Arab Emirates',
    GB = 'United Kingdom',
    US = 'United States',
    UM = 'United States Outlying Islands',
    UY = 'Uruguay',
    UZ = 'Uzbekistan',
    VU = 'Vanuatu',
    VE = 'Venezuela',
    VN = 'Vietnam',
    VG = 'Virgin Islands British',
    VI = 'Virgin Islands US',
    WF = 'Wallis And Futuna',
    EH = 'Western Sahara',
    YE = 'Yemen',
    ZM = 'Zambia',
    ZW = 'Zimbabwe'
}

export enum State {
    AK = 'Alaska',
    AL = 'Alabama',
    AR = 'Arkansas',
    AZ = 'Arizona',
    CA = 'California',
    CO = 'Colorado',
    CT = 'Connecticut',
    DE = 'Delaware',
    FL = 'Florida',
    GA = 'Georgia',
    HI = 'Hawaii',
    IA = 'Iowa',
    ID = 'Idaho',
    IL = 'Illinois',
    IN = 'Indiana',
    KS = 'Kansas',
    KY = 'Kentucky',
    LA = 'Louisiana',
    MA = 'Massachusetts',
    MD = 'Maryland',
    ME = 'Maine',
    MI = 'Michigan',
    MN = 'Minnesota',
    MO = 'Missouri',
    MS = 'Mississippi',
    MT = 'Montana',
    NC = 'NorthCarolina',
    ND = 'NorthDakota',
    NE = 'Nebraska',
    NH = 'NewHampshire',
    NJ = 'NewJersey',
    NM = 'NewMexico',
    NV = 'Nevada',
    NY = 'NewYork',
    OH = 'Ohio',
    OK = 'Oklahoma',
    OR = 'Oregon',
    PA = 'Pennsylvania',
    RI = 'RhodeIsland',
    SC = 'SouthCarolina',
    SD = 'SouthDakota',
    TN = 'Tennessee',
    TX = 'Texas',
    UT = 'Utah',
    VA = 'Virginia',
    VT = 'Vermont',
    WA = 'Washington',
    WI = 'Wisconsin',
    WV = 'WestVirginia',
    WY = 'Wyoming'
}
