INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'daguirre', 'Daniel', 'Aguirre', 'daguirre@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'aakhtar', 'Ahmed', 'Akhtar', 'aakhtar@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'bal-sharif', 'Bashar', 'Al-Sharif', 'bal-sharif@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'balarcon', 'Brenda', 'Alarcon', 'balarcon@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mallegretti', 'Michael', 'Allegretti', 'mallegretti@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'talmuti', 'Travis', 'Almuti', 'talmuti@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mamajor', 'Madu', 'Amajor', 'mamajor@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'bamerson', 'Bryan', 'Amerson', 'bamerson@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ganaya', 'Guillermo', 'Anaya', 'ganaya@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'aaperture', 'Aviation', 'Aperture', 'aaperture@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'carcuri', 'Craig', 'Arcuri', 'carcuri@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rator', 'Riccardo', 'Ator', 'rator@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rbaba', 'Ross', 'Baba', 'rbaba@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'kbaiocchi', 'Ken', 'Baiocchi', 'kbaiocchi@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'abaliscao', 'Adrian', 'Baliscao', 'abaliscao@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rbandy', 'Richard', 'Bandy', 'rbandy@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'abantug', 'Alexander', 'Bantug', 'abantug@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jbarker', 'James', 'Barker', 'jbarker@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jbarriga', 'Jorge', 'Barriga', 'jbarriga@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'obaser', 'Orhan', 'Baser', 'obaser@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rbasu', 'Rituparna', 'Basu', 'rbasu@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mbatshon', 'Michael', 'Batshon', 'mbatshon@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'obetgorgiz', 'Obalit', 'Betgorgiz', 'obetgorgiz@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'pbe_a_pilot', 'Program', 'Be_a_pilot', 'pbe_a_pilot@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rbhandari', 'Rahul', 'Bhandari', 'rbhandari@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jbird', 'James', 'Bird', 'jbird@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'tbirnschein', 'Timo', 'Birnschein', 'tbirnschein@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'gblom', 'Gary', 'Blom', 'gblom@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ibohorquez', 'Ian', 'Bohorquez', 'ibohorquez@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'aboiteux-levret', 'Andre', 'Boiteux-Levret', 'aboiteux-levret@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dboyd', 'David', 'Boyd', 'dboyd@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jbradley', 'Julia', 'Bradley', 'jbradley@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'gbranche', 'Gregory', 'Branche', 'gbranche@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'fbrennan', 'Francis', 'Brennan', 'fbrennan@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rbuergis', 'Roger', 'Buergis', 'rbuergis@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'tcamp', 'Thomas', 'Camp', 'tcamp@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ccarey', 'Chris', 'Carey', 'ccarey@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'gcarr', 'Gordon', 'Carr', 'gcarr@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dcase', 'Daniel', 'Case', 'dcase@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jcastaneda', 'Jimmy', 'Castaneda', 'jcastaneda@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'achakraborty', 'Arpan', 'Chakraborty', 'achakraborty@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'schan', 'Sin Yee', 'Chan', 'schan@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ichantzis', 'Ilias', 'Chantzis', 'ichantzis@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rcharan', 'Ram', 'Charan', 'rcharan@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mchavan', 'Mihir', 'Chavan', 'mchavan@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'lcherbel', 'Lotfi', 'Cherbel', 'lcherbel@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'achiang', 'Alex', 'Chiang', 'achiang@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'cchiau', 'Charles', 'Chiau', 'cchiau@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'hchien', 'Howard', 'Chien', 'hchien@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'cchung', 'Chi Ting', 'Chung', 'cchung@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jcohen', 'Jack', 'Cohen', 'jcohen@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'tcolvin', 'Timothy', 'Colvin', 'tcolvin@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'bconlisk', 'Brian', 'Conlisk', 'bconlisk@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'bconnelly', 'Barrett', 'Connelly', 'bconnelly@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'aconrad', 'Ariel', 'Conrad', 'aconrad@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'scooksy', 'Sean', 'Cooksy', 'scooksy@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jcorgan', 'John', 'Corgan', 'jcorgan@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ecorlett', 'Evelyn', 'Corlett', 'ecorlett@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mcoulibaly', 'Mack', 'Coulibaly', 'mcoulibaly@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'tcroley', 'Tyler', 'Croley', 'tcroley@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'gcrothall', 'George', 'Crothall', 'gcrothall@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'gcummings', 'Garth', 'Cummings', 'gcummings@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ddalberg', 'Darrall', 'Dalberg', 'ddalberg@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ndaley', 'Nigel', 'Daley', 'ndaley@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ddamle', 'Dipty', 'Damle', 'ddamle@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'adavis', 'Auston', 'Davis', 'adavis@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jdavis', 'Jason', 'Davis', 'jdavis@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jdean', 'James', 'Dean', 'jdean@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'bdelph', 'Bryson', 'Delph', 'bdelph@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jdrewery', 'John', 'Drewery', 'jdrewery@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'aduff', 'Andrew', 'Duff', 'aduff@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rdumais', 'Robert', 'Dumais', 'rdumais@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mduong', 'Michael', 'Duong', 'mduong@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'serman', 'Sean', 'Erman', 'serman@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'sermolin', 'Sergey', 'Ermolin', 'sermolin@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mervin', 'Michael', 'Ervin', 'mervin@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'heul', 'Hermann Josef', 'Eul', 'heul@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rfarinelli', 'Randall', 'Farinelli', 'rfarinelli@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'cfaul', 'Clayton', 'Faul', 'cfaul@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mformica', 'Michael', 'Formica', 'mformica@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'cfoss', 'Colbjoern', 'Foss', 'cfoss@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'egabel', 'Edward', 'Gabel', 'egabel@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rgaumont', 'Reece', 'Gaumont', 'rgaumont@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ogila', 'Omer', 'Gila', 'ogila@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'pgogineni', 'Prasada', 'Gogineni', 'pgogineni@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'agonzalez', 'Antonio', 'Gonzalez', 'agonzalez@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'igregg', 'Ian', 'Gregg', 'igregg@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'pgrobelny', 'Patrycjusz', 'Grobelny', 'pgrobelny@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mgross', 'Michael', 'Gross', 'mgross@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'vguerra', 'Vyncent', 'Guerra', 'vguerra@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'wgyger', 'Walter', 'Gyger', 'wgyger@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mhaman', 'Michael', 'Haman', 'mhaman@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dharris', 'Darryl', 'Harris', 'dharris@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'lharvey', 'Landon', 'Harvey', 'lharvey@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'zheineman', 'Zachary', 'Heineman', 'zheineman@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ahenderson', 'Alexander', 'Henderson', 'ahenderson@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'iherbert', 'Ian', 'Herbert', 'iherbert@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'chernandez', 'Cesar', 'Hernandez', 'chernandez@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jhernandez', 'Jason', 'Hernandez', 'jhernandez@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'nhightower', 'Nicholas', 'Hightower', 'nhightower@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ahobbs', 'Alan', 'Hobbs', 'ahobbs@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jhodgson', 'John', 'Hodgson', 'jhodgson@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'chofstetter', 'Craig', 'Hofstetter', 'chofstetter@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'thornak', 'Tom', 'Hornak', 'thornak@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'phornberger', 'Patrick', 'Hornberger', 'phornberger@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rhosking', 'Ryan', 'Hosking', 'rhosking@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'thwang', 'Taeho', 'Hwang', 'thwang@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ehyde', 'Elizabeth', 'Hyde', 'ehyde@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rjain', 'Reshu', 'Jain', 'rjain@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mjankowski', 'Michal', 'Jankowski', 'mjankowski@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ajavier', 'Aries Alfred', 'Javier', 'ajavier@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'cjung', 'Chanyoung', 'Jung', 'cjung@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jjung', 'Jae Hoon', 'Jung', 'jjung@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'sjurescu', 'Simona', 'Jurescu', 'sjurescu@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'nkalyankar', 'Nikhil', 'Kalyankar', 'nkalyankar@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jkang', 'Jinglong', 'Kang', 'jkang@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'vkapur', 'Vikas', 'Kapur', 'vkapur@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jkarandonis', 'John', 'Karandonis', 'jkarandonis@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'akarpuram', 'Abhishek', 'Karpuram', 'akarpuram@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'akatiyar', 'Abhinav', 'Katiyar', 'akatiyar@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jkaur', 'Jashanpreet', 'Kaur', 'jkaur@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rkaur', 'Ranjeet', 'Kaur', 'rkaur@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'nkhatwani', 'Neeraj', 'Khatwani', 'nkhatwani@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'pkhatwani', 'Prisha', 'Khatwani', 'pkhatwani@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mkhitrykh', 'Mikhail', 'Khitrykh', 'mkhitrykh@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'hkim', 'Hong Suk', 'Kim', 'hkim@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mkim', 'Myoung-Chang', 'Kim', 'mkim@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dkim', 'Daesung', 'Kim', 'dkim@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ckoester', 'Carsten', 'Koester', 'ckoester@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'lkomarek', 'Lucas', 'Komarek', 'lkomarek@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mkucherawy', 'Murray', 'Kucherawy', 'mkucherawy@flytrainer.com',1,0,0,0,0,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'pkvitek', 'Peter', 'Kvitek', 'pkvitek@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mkwak', 'Melanie', 'Kwak', 'mkwak@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'blai', 'Biaoshuai', 'Lai', 'blai@flytrainer.com',1,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'plamar', 'Phil', 'LaMar', 'plamar@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mlarge', 'Matthew', 'Large', 'mlarge@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'blarochelle', 'Brian', 'LaRochelle', 'blarochelle@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'plearmonth', 'Peter', 'Learmonth', 'plearmonth@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rlee', 'Ryan', 'Lee', 'rlee@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'wlee', 'William', 'Lee', 'wlee@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jlee', 'Jongho', 'Lee', 'jlee@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'wlee2', 'Weonho', 'Lee', 'wlee2@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'clee', 'Changhoon', 'Lee', 'clee@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dlee', 'Daesub', 'Lee', 'dlee@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'oleipelt', 'Owen', 'Leipelt', 'oleipelt@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'nleiva abarca', 'Nery', 'Leiva Abarca', 'nleiva abarca@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'wli', 'Wanli', 'Li', 'wli@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'xli', 'Xi', 'Li', 'xli@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jliao', 'Jianhua', 'Liao', 'jliao@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'klin', 'Kai', 'Lin', 'klin@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'flin', 'Fei', 'Lin', 'flin@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rlin', 'Randolph', 'Lin', 'rlin@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dliu', 'Di', 'Liu', 'dliu@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jliu', 'Jacky', 'Liu', 'jliu@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'sloose', 'Sam', 'Loose', 'sloose@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dmack', 'Donald', 'Mack', 'dmack@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'hmagganmane', 'Harish', 'Magganmane', 'hmagganmane@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mmaint', 'MARK CROUCH', 'Maint', 'mmaint@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'bmammadov', 'Bakhtiyar', 'Mammadov', 'bmammadov@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jmarconet', 'Jeff', 'Marconet', 'jmarconet@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ymartinez mendoza', 'Yudit', 'Martinez Mendoza', 'ymartinez mendoza@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'fmasavion ltd', 'Frank', 'Masavion Ltd', 'fmasavion ltd@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'pmassoud', 'Philip', 'Massoud', 'pmassoud@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'tmeads', 'Trevor', 'Meads', 'tmeads@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jmiller', 'Jeffrey', 'Miller', 'jmiller@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rmitra', 'Ranadeb', 'Mitra', 'rmitra@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'bmohammad', 'Barrat', 'Mohammad', 'bmohammad@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'amonsale', 'Aeron', 'Monsale', 'amonsale@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'nmorozov', 'Nikolai', 'Morozov', 'nmorozov@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jmuguerza', 'Jose', 'Muguerza', 'jmuguerza@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'zmulcahy', 'Zachary', 'Mulcahy', 'zmulcahy@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'bmull', 'Benjamin', 'Mull', 'bmull@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jmumy', 'John', 'Mumy', 'jmumy@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jmurphy', 'James', 'Murphy', 'jmurphy@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'amurray', 'Aaron', 'Murray', 'amurray@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dmurray', 'Daniel', 'Murray', 'dmurray@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jmyung', 'John', 'Myung', 'jmyung@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rnair', 'Ratish', 'Nair', 'rnair@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'tnguyen', 'Tri', 'Nguyen', 'tnguyen@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mnguyen', 'Michael', 'Nguyen', 'mnguyen@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'knguyen', 'Khanh', 'Nguyen', 'knguyen@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'nnguyen', 'Nhat', 'Nguyen', 'nnguyen@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'tnguyen2', 'Thanh', 'Nguyen', 'tnguyen2@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'anguyen', 'Anh Ngoc', 'Nguyen', 'anguyen@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'gniva', 'Gary', 'Niva', 'gniva@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dnorton', 'David', 'Norton', 'dnorton@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jolsen', 'Jacob', 'Olsen', 'jolsen@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'aomar', 'Ahmed', 'Omar', 'aomar@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'soueini', 'Shafic', 'Oueini', 'soueini@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dpan', 'Dong', 'Pan', 'dpan@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dpastore', 'David', 'Pastore', 'dpastore@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ypatel', 'Yash', 'Patel', 'ypatel@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'epeterson', 'Eric', 'Peterson', 'epeterson@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'spetursson', 'Sigurdur', 'Petursson', 'spetursson@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'bpham', 'Brian', 'Pham', 'bpham@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'yposada portillo', 'Yesica', 'Posada Portillo', 'yposada portillo@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mproperzi', 'Michele', 'Properzi', 'mproperzi@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'xpu', 'Xi', 'Pu', 'xpu@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'vraghavan', 'Vijay', 'Raghavan', 'vraghavan@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dramos', 'Devin', 'Ramos', 'dramos@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rrancy', 'Runnu', 'Rancy', 'rrancy@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'craymer', 'Chloe', 'Raymer', 'craymer@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'lrazera', 'Luiz', 'Razera', 'lrazera@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'lreed', 'Lawrence', 'Reed', 'lreed@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mreuven', 'Moshe', 'Reuven', 'mreuven@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ireuven', 'Itamar', 'Reuven', 'ireuven@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'gritz', 'Graham', 'Ritz', 'gritz@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'trobinson', 'Ted', 'Robinson', 'trobinson@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'arodriguez lopez', 'Adan', 'Rodriguez Lopez', 'arodriguez lopez@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'krowe', 'Keja', 'Rowe', 'krowe@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'truedisuehli', 'Thomas', 'Ruedisuehli', 'truedisuehli@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rruiz jr', 'Rogelio', 'Ruiz Jr', 'rruiz jr@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'nrussell', 'Neil', 'Russell', 'nrussell@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jsalas', 'Juan', 'Salas', 'jsalas@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'psarma', 'Pratheek', 'Sarma', 'psarma@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'bscarbrough', 'Bob', 'Scarbrough', 'bscarbrough@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rscholz', 'Richard', 'Scholz', 'rscholz@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'asehmbey', 'Amandip', 'Sehmbey', 'asehmbey@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ssharma', 'Siddhant', 'Sharma', 'ssharma@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'sshaw', 'Samuel', 'Shaw', 'sshaw@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'psheiki nassab', 'Pezhman', 'Sheiki nassab', 'psheiki nassab@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'gshen', 'GuanYan', 'Shen', 'gshen@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'vsilva', 'Vincent', 'Silva', 'vsilva@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jsim', 'Jordi', 'Sim', 'jsim@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ssingh', 'Sandeep', 'Singh', 'ssingh@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'asingh', 'Amandeep', 'Singh', 'asingh@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'tsirmons', 'Troy', 'Sirmons', 'tsirmons@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'fsison', 'Francis', 'Sison', 'fsison@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'hsiviya', 'Hazurasingh', 'Siviya', 'hsiviya@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dslabodar', 'Daniil', 'Slabodar', 'dslabodar@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'nsnyder', 'Nakela', 'Snyder', 'nsnyder@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jsoule', 'Jeff', 'Soule', 'jsoule@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'nstamber', 'Nicolas', 'Stamber', 'nstamber@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'tsterling', 'Todd', 'Sterling', 'tsterling@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'fsu', 'Feiqi', 'Su', 'fsu@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'psullivan', 'Patrick', 'Sullivan', 'psullivan@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'kswanson', 'Kevin', 'Swanson', 'kswanson@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'esynodinos', 'Emanuel', 'Synodinos', 'esynodinos@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ptalamantez', 'Peter', 'Talamantez', 'ptalamantez@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'atijani', 'Andrew', 'Tijani', 'atijani@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jtobin', 'Jeffrey', 'Tobin', 'jtobin@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ktodd', 'Kelly', 'Todd', 'ktodd@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'stoor', 'Sidharth', 'Toor', 'stoor@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dtozer', 'David', 'Tozer', 'dtozer@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ctozer', 'Christopher', 'Tozer', 'ctozer@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ttran', 'Tiem', 'Tran', 'ttran@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mtrimpl', 'Marcel', 'Trimpl', 'mtrimpl@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mtrivedi', 'Mihir', 'Trivedi', 'mtrivedi@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ptrivedi', 'Paras', 'Trivedi', 'ptrivedi@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ctrivellore', 'Charan', 'Trivellore', 'ctrivellore@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'btruong', 'Brian', 'Truong', 'btruong@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dtsang', 'David', 'Tsang', 'dtsang@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ntsukui', 'Naoki', 'Tsukui', 'ntsukui@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'mturney', 'Mike', 'Turney', 'mturney@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'oubilla', 'Omar', 'Ubilla', 'oubilla@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'bvan veen', 'Bas', 'Van Veen', 'bvan veen@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rvelasco', 'Ricardo', 'Velasco', 'rvelasco@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'aveldman', 'Anna', 'Veldman', 'aveldman@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rvillalobos', 'Rio', 'Villalobos', 'rvillalobos@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'avillalobos', 'Antonio', 'Villalobos', 'avillalobos@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jvinh', 'Jason', 'Vinh', 'jvinh@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'nwaghmare', 'Nikhil', 'Waghmare', 'nwaghmare@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ywan', 'YU JEN', 'WAN', 'ywan@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'lwang', 'Liang Ya', 'Wang', 'lwang@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jwatson', 'Josh', 'Watson', 'jwatson@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jwaugh', 'Jason', 'Waugh', 'jwaugh@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'vwawrzynski', 'Vincent', 'Wawrzynski', 'vwawrzynski@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jwelborn', 'John', 'Welborn', 'jwelborn@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'rwhite', 'Richard', 'White', 'rwhite@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dwhite', 'Dean', 'White', 'dwhite@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'cwiegand', 'Chandler', 'Wiegand', 'cwiegand@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'wwright', 'Wilbur', 'Wright', 'wwright@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'cwu', 'Chiu Wa', 'Wu', 'cwu@flytrainer.com',0,0,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'yxing', 'Yuxuan', 'Xing', 'yxing@flytrainer.com',0,0,0,1,1,0,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jyang', 'Justin', 'Yang', 'jyang@flytrainer.com',1,0,0,1,1,0,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'sying', 'Shangcheng', 'Ying', 'sying@flytrainer.com',1,0,0,1,1,0,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'gyuen', 'George', 'Yuen', 'gyuen@flytrainer.com',1,0,0,1,1,0,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'jyuen', 'Joe', 'Yuen', 'jyuen@flytrainer.com',1,1,0,1,1,0,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ezakharov', 'Evgeny', 'Zakharov', 'ezakharov@flytrainer.com',1,1,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'szandbergen', 'Sabrina', 'Zandbergen', 'szandbergen@flytrainer.com',1,1,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'ezen', 'Edward', 'Zen', 'ezen@flytrainer.com',1,1,0,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'wzhang', 'Wentao', 'Zhang', 'wzhang@flytrainer.com',1,1,1,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'czhang', 'Chris', 'Zhang', 'czhang@flytrainer.com',1,1,1,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'xzhang', 'Xiang', 'Zhang', 'xzhang@flytrainer.com',1,1,1,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'dzhao', 'Dongsheng', 'Zhao', 'dzhao@flytrainer.com',1,1,1,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'czhou', 'Chunnyang', 'Zhou', 'czhou@flytrainer.com',1,1,1,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO flytrainer.user(uuid, username, firstname, lastname, email, active, resetpassword, employee, citizen, proficient, member, role, version, password, created_date, modified_date) VALUES (UUID(), 'hzhou', 'Henry', 'Zhou', 'hzhou@flytrainer.com',1,1,1,1,1,1,0,1,'Welcome1',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());


--  Update other columns --
SET @MIN = '1920-01-31 00:00:00';
SET @MAX = '2004-01-31 00:00:00';
UPDATE flytrainer.user SET birthday=TIMESTAMPADD(SECOND, FLOOR(RAND() * TIMESTAMPDIFF(SECOND, @MIN, @MAX)), @MIN) WHERE id != 0;

UPDATE flytrainer.user SET driver_license_exp_date=TIMESTAMPADD(SECOND, FLOOR(RAND() * TIMESTAMPDIFF(SECOND, @MIN, @MAX)), @MIN) WHERE id != 0;

UPDATE flytrainer.user SET middlename='N/A' WHERE id != 0;

UPDATE flytrainer.user SET driver_license=concat('B', round(rand()*9999999 + 1000000)) WHERE id != 0;

UPDATE flytrainer.user SET ftn=concat('A', round(rand()*9999999 + 1000000)) WHERE id != 0;

UPDATE flytrainer.user SET driver_license_state=SUBSTRING('AKALARAZCACOCTDEFLGAHIIAIDIL',  (floor((RAND() * 13)) * 2) + 1, 2) WHERE id != 0;

UPDATE flytrainer.user SET ssn=concat(
   6,
   round(rand()*9),
   round(rand()*9),
   round(rand()*9),
   round(rand()*9),
   round(rand()*9),
   round(rand()*9),
   round(rand()*9),
   round(rand()*9)
) WHERE id != 0;

UPDATE flytrainer.user SET cellphone=concat(
   '(',
   round(rand()*9),
   round(rand()*9),
   round(rand()*9),
   ') ',
   round(rand()*9),
   round(rand()*9),
   round(rand()*9),
   '-',
   round(rand()*9),
   round(rand()*9),
   round(rand()*9),
   round(rand()*9)
) WHERE id != 0;