name: Flight School Management System - Build

#https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-azure-pipelines-to-github-actions

on:
  push:
    branches: ['master']

jobs:
  wait:
    uses: ./.github/workflows/prebuild.yml
    name: Wait Prebuild

  tree:
    needs: wait
    name: Job3
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - run: echo "This step DEV"
        shell: bash
  four:
    needs: wait
    name: Job4
    environment: 
      name: QA
      url: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "This step QA"
        shell: bash
      - name: "checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Added file prebuild.yaml
            - Added file app.yaml
          draft: false
          prerelease: false
      - name: "cleanup"
        run: |
          echo ${{ github.ref }}
      