name: Flight School Management System

on:
  push:
    branches: ['master']

jobs:
  one:
    name: Job1
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - run: echo "This step runs in the default shell"
      - run: echo "This step runs in bash"
        shell: bash
  two:
    name: Job2
    runs-on: ubuntu-latest
    steps:
      - run: echo "This step runs in the default shell"
        name: Step1
      - run: echo "This step runs in bash"
        name: Step2
        shell: bash