name: Flight School Management System - Build

#https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-azure-pipelines-to-github-actions

on:
  push:
    branches: ['master']

jobs:
  one:
    uses: dgofman/flytrainer/.github/workflows/prebuild.yml@master
    name: Job1
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - run: echo "This step runs in the default shell"
      - run: echo "This step runs in bash"
        shell: bash
  two:
    name: Job2
    needs: one
    runs-on: ubuntu-latest
    steps:
      - run: echo "This step runs in the default shell"
        name: Step1
      - run: echo "This step runs in bash"
        name: Step2
        shell: bash