name: Flight School Management System - Build

#https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-azure-pipelines-to-github-actions

on:
  push:
    branches: ['master']

jobs:
  wait:
    uses: ./.github/workflows/prebuild.yml
    name: Wait Prebuild

  tree:
    needs: wait
    name: Job3
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - run: echo "This step DEV"
        shell: bash
  four:
    needs: wait
    name: Job4
    environment: QA
    runs-on: ubuntu-latest
    steps:
      - run: echo "This step QA"
        shell: bash